#!/bin/bash

source validate.sh

# This script automates the setup of a basic web server environment

if [ ! $EUID -eq 0 ] || [ ! -n "$SUDO_COMMAND" ]; then
	echo "This script must be run as root or with sudo." >&2
	exit 1
fi

while true; do
	read -p "Choose server to install (1 for Apache, 2 for Nginx): " choice
	if validate_choice "$choice"; then
		break
	fi
done

while true; do
        read -p "Enter a hostname: " hname
        if validate_hostname "$hname"; then
                break
        fi
done

echo " "
echo "Updating Package Index"

sudo apt update -y
if [ $? -ne 0 ]; then
	echo "Error: Failed to update packages." >&2
	exit 1
fi

echo " "
echo "Installing $server_name"

sudo apt install "$server_name"
if [ $? -ne 0 ]; then
        echo "Error: Failed to install $server_name." >&2
        exit 1
fi

echo ""
echo "Creating default index.html page"
touch index.html
if [ $? -ne 0 ]; then
	echo "Server created"
        echo "Error: Failed to create index.html" >&2
        exit 1
fi

: << 'END_COMMENT'
cat <<EOF > index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello, World!</title>
</head>
<body>
    <h1>Hello, World!</h1>
    <p>This is a simple HTML page served by $(capitalize_first_letter "$server_name").</p>
</body>
</html>
EOF

echo "index.html file created"
END_COMMENT
