#!/bin/bash

# This script will be used for user and group management

source validate.sh

cat <<EOF
Hi! Here are our options!

A) Create a user account
B) Delete a user account
C) Change supplementary group for a user account
D) Change initial group for a user account
E) Change default login shell for a user account
F) Change account expiration date for a user account
Q) Quit

EOF

: << 'END_COMMENT'
read -p "What would you like to do today?: " user_input

echo $user_input

validate_input "$user_input"
END_COMMENT

while true; do
	read -p "What would you like to do today?: " user_input
	if validate_input "$user_input"; then
		break
	else 
		echo "Invalid option"
	fi
done

echo "you made it here"
