#!/bin/bash

# This script will be used for user and group management

source validate.sh
source user_utils.sh

cat <<EOF
Hi! Here are our options!

A) Create a user account
B) Delete a user account
C) Change supplementary group for a user account
D) Change initial group for a user account
E) Change default login shell for a user account
F) Change account expiration date for a user account
Q) Quit

EOF

while true; do
	read -p "What would you like to do today?: " user_input
	if validate_input "$user_input"; then
		break
	else 
		echo "Invalid option"
	fi
done

echo ""

if [ $user_input == 'A' ] || [ $user_input == 'a' ]; then
	create_user_account
elif [ $user_input == 'B' ] || [ $user_input == 'b' ]; then
        delete_user_account
elif [ $user_input == 'C' ] || [ $user_input == 'c' ]; then
        change_supplementary_group
elif [ $user_input == 'D' ] || [ $user_input == 'd' ]; then
        change_initial_group
elif [ $user_input == 'E' ] || [ $user_input == 'e' ]; then
        change_default_shell
elif [ $user_input == 'F' ] || [ $user_input == 'f' ]; then
        change_account_expiration_date
elif [ $user_input == 'Q' ] || [ $user_input == 'q' ]; then
        echo "Goodbye!"
	exit 0
else
	echo "Something went wrong, please try again"
	exit 1
fi
